config/routes.rb
Monju::Application.routes.draw do
  resources :troop_definitions do

    member do
      get :validation
      get :parse
      get :value_check_list
      get :diff_form
    end

  end

  resources :npc_name_list
  resources :object_definitions
  resources :common_definitions , controller: :object_definitions , type: 'CommonDefinition'

  resources :specifications do
    collection do
      post :move_position
    end


  end

  resources :organizations
  resources :knights
  resources :adventurers_guild
  resources :advance_bases
  resources :individual_knights
  resources :corporations
  resources :other_orgs
  resources :aces do
    collection do
      get :items
      get :items_for_wiki
    end


  end

  resources :roles
  resources :i_definitions

  resources :nations do
    collection do
      get :top
      get :associated   , :action => :associated_nations_list
    end
    member do
      get :miles
    end
    resources :characters
    resources :collection
    resources :idress_wearing_tables do

      member do
        post :edit
        get :copy
        get :restriction_check
        get :vcc_format
      end

    end
  end

#  resources :mile_changes
  resources :owner_accounts do
#    get :facade
    collection do
      get :facade
      get :update_form_parts
      get :confirm
    end
    member do
      get :update_owner_account_list
      post :process_edit
    end

    resources :cash_records do
      collection do
        get :import_form
        post :import_select_table
        post :move_position
      end
    end

    resources :weapon_registries do
      collection do
        post :move_position
      end
    end

    resources :object_registries do
      collection do
        post :move_position
        get :wiki_output
      end
    end

    resources :job_idresses
    resources :mile_changes
    resources :yggdrasills

    resources :command_resources

    resources :unit_registries do
      member do
        get :rebuild
        get :disable
      end
    end
  end

  resources :unit_registries

  resources :yggdrasills do
    member do
      post :move
    end
  end

  resources :characters do
    collection do
      get :bonus_list
      post :move_position
    end
    member do
      get :acquired_idresses
      post :append_acquired_idress
      delete :remove_acquired_idress
      get :edit_note_for_acquirement
      put :update_note_for_acquirement
    end
    resources :bonds
  end

  resources :modify_commands

  match 'owner_accounts/:owner_account_id/weapons' => 'weapons#index' , :as => :weapons
  match 'owner_accounts/:owner_account_id/modify_commands' => 'modify_commands#index' , :as => :owner_account_modify_commands

  match 'taigen/compile.:format' => 'taigen#compile', :defaults => {:format => 'js'}

  match 'search/command_resources.:format' => 'search#command_resources' , defaults: {format: :js}
  match ':controller/service.wsdl' => '#wsdl'
  match '/:controller(/:action(/:id))'

end

app/models/mile_change.rb
class MileChange < ActiveRecord::Base
  attr_accessible :mile , :reason , :application_url ,:ground_url , :owner_account_id,
                  :note , :turn

  belongs_to :owner_account
  has_many :modify_commands , :as => :target
  
  validates_presence_of :mile
  validates_numericality_of :mile

#  include ModifyRecordable

  after_save :update_owner_miles
  before_destroy :refuge_owner_account
  after_destroy :update_owner_miles
  def update_owner_miles
    owner = @owner_account_obj || self.owner_account
    owner && owner.update_miles
  end
  
  def refuge_owner_account
    @owner_account_obj = self.owner_account
  end
  
  #def after_destroy
  #  @owner_account_obj.update_miles if @owner_account_obj
  #end
end

app/controllers/mile_changes_controller.rb
# -*- encoding: utf-8 -*-
class MileChangesController < ApplicationController
  cache_sweeper :modify_sweeper , :only => [:create , :destroy , :update]
  requires_role :accountant , :only => [:create , :update  , :destroy ]
  set_login_filter

  # GET /mile_changes
  # GET /mile_changes.xml
  def index
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @limit = case
    when  params[:limit]== 'all'
      nil
    when params[:limit].nil?
      100
    else
      params[:limit].to_i
    end
    if params[:turn]
      @target_turn = params[:turn]
      @count = nil
      if @target_turn == 'last'
        turn = Property['current_turn'].to_i + 1
        if MileChange.count(:conditions => ["owner_account_id = ?" , params[:owner_account_id] ]) == 0
          turn = Property['current_turn'].to_i
        else
          while @count.nil? || @count == 0
            turn -= 1
            @count = MileChange.count(:conditions => ["owner_account_id = ? and turn = ?" , params[:owner_account_id] , turn])
          end
        end
        @target_turn = turn
      else
        @count = MileChange.count(:conditions => ["owner_account_id = ? and turn = ?" , params[:owner_account_id] , @target_turn] )
      end

      opts = if @count && @limit && @count > @limit
        @offset = params[:offset] || (@count - @limit)
        @offset = @offset.to_i
        {:limit => (@offset.to_i + @limit.to_i)}
      else
        @offset = nil
        {}
      end
      result = MileChange.find_all_by_owner_account_id_and_turn(params[:owner_account_id] , @target_turn ,opts.merge(:order => :id) )
      @mile_changes = if @offset
        result[@offset , @limit]
      else
        result
      end


      @zandaka = MileChange.find_by_sql(['select sum(mile) as miles  from mile_changes where owner_account_id = ? and turn < ? ' ,
        params[:owner_account_id] ,@target_turn ])[0]

      if @offset && @zandaka
        @zandaka2 =  result[0...@offset].inject(0){|result,item| result += item.mile}

        @zandaka.miles = @zandaka.miles.to_i + @zandaka2
      end
    elsif params[:date]
      y , m , d = params[:date].split('-').map{|i|i.to_i}
      day = Date.new(y, m , d)
      @mile_changes = MileChange.find_all_by_owner_account_id(params[:owner_account_id] , :conditions => ['date(created_at) = ?' , day])
      @zandaka = MileChange.find_by_sql(['select sum(mile) as miles from mile_changes where owner_account_id = ? and created_at < ?' ,
        params[:owner_account_id] , day])[0]
    else
      @mile_changes = @owner_account.mile_changes
    end
    @mile_changes = @mile_changes.sort_by(&:created_at)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mile_changes }
    end
  end

  # GET /mile_changes/1
  # GET /mile_changes/1.xml
  def show
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @mile_change = MileChange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mile_change }
    end
  end

  # GET /mile_changes/new
  # GET /mile_changes/new.xml
  def new
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @mile_change = MileChange.new
    @mile_change.turn = Property[:current_turn].to_i
    @mile_change.owner_account = @owner_account
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mile_change }
    end
  end

  # GET /mile_changes/1/edit
  def edit
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @mile_change = MileChange.find(params[:id])
  end

  # POST /mile_changes
  # POST /mile_changes.xml
  def create
    @owner_account = OwnerAccount.find(params[:mile_change][:owner_account_id])
    @mile_change = MileChange.new(params[:mile_change])
    respond_to do |format|
      if @mile_change.save
        flash[:notice] = 'マイル口座に項目を追加しました。'
        format.html {
          if @mile_change.turn.to_i > 0
            redirect_to(owner_account_mile_changes_path(@owner_account,:turn => @mile_change.turn))
          else
            redirect_to(owner_account_mile_changes_path(@owner_account))
          end
        }
        format.xml  { render :xml => @mile_change, :status => :created, :location => @mile_change }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mile_change.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mile_changes/1
  # PUT /mile_changes/1.xml
  def update
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @mile_change = MileChange.find(params[:id])

    respond_to do |format|
      if @mile_change.update_attributes(params[:mile_change])
        flash[:notice] = 'マイル口座の項目内容を変更しました。'
        format.html {
          if @mile_change.turn.to_i > 0
            redirect_to(owner_account_mile_changes_path(@owner_account,:turn => @mile_change.turn))
          else
            redirect_to(owner_account_mile_changes_path(@owner_account))
          end
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mile_change.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mile_changes/1
  # DELETE /mile_changes/1.xml
  def destroy
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @mile_change = MileChange.find(params[:id])
    @mile_change.destroy

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/mile_changes_helper.rb
module MileChangesHelper
end

app/views/mile_changes/_form.html.erb

<table>
<tr>      
  <td align=right>  事由：</td> 
  <td> <%= f.text_field  :reason ,:size => 60%>  </td>
  </tr>
  <tr>
    <td align=right>マイル変動：</td>
    <td><%= f.text_field  :mile , :size => 3 %> </td>
  </tr>
  <tr>
    <td align=right>備考：</td>
    <td><%= f.text_area  :note , :rows => 5 , :cols => 60  %> </td>
  </tr>
  <tr>
    <td align=right>申請URL：</td>
    <td><%= f.text_field  :application_url , :size => 80 %> </td>
  </tr>
  <tr>
    <td align=right>根拠URL：</td>
    <td><%= f.text_field  :ground_url , :size => 80 %> </td>
  </tr>
  <tr>
    <td align=right>ターン：</td>
    <td><%= f.text_field  :turn , :size => 3 %> </td>
  </tr>
</table>
<%= f.hidden_field :owner_account_id  %>


app/views/mile_changes/create.html.erb
<h1>MileChanges#create</h1>
<p>Find me in app/views/mile_changes/create.html.erb</p>

app/views/mile_changes/edit.html.erb
<h1>マイル出納履歴の編集</h1>

<%= error_messages_for :mile_change %>

<%= form_for( @mile_change , :url => owner_account_mile_change_path(@owner_account ,  @mile_change)  ) do |f| %>

  <%= render :partial => 'form' ,:locals => { :f => f }%>
  <%= f.submit "Update" %>
<% end %>

<%= link_to '[ 戻る ]', owner_account_mile_changes_path(@mile_change.owner_account , turn: @mile_change.turn ) %>

app/views/mile_changes/index.html.erb
<h2> <%= @owner_account.owner.name %> マイル口座</h2>
<% if controller.has_role?(:accountant) -%>
<%= button_to '新規マイル出納', new_owner_account_mile_change_path(@owner_account) , :method => :get %>
<% end -%>
<br/>
ターン：<%= turn_link(@target_turn) %>
<% if @offset || params[:limit] == 'all'%>
<br/> 
<%= offset_link(@count , @target_turn , @limit) %>
<% end %>
<table border=1>
  <tbody>
  <tr>
    <th>日時</th> <th> 事由 </th> <th> マイル収入 </th> <th> マイル支出 </th><th> 備考 </th> <th> 申請 </th> <th> 根拠 </th> <th> ターン </th> 
  </tr>

<% sum = 0 
  plus = 0
  minus = 0
%>
<% if @zandaka %>
  <tr>
    <td> </td>
    <td> 繰り越し </td>
    <td align=right> <%= @zandaka.miles %> </td>
    <td> </td>
    <td> </td>
    <td> </td>
    <td> </td>
  </tr>
  
<% plus += @zandaka.miles.to_i

  end -%>
<% for changes in @mile_changes%>
  <tr>
  	<td><%= link_to(changes.created_at.strftime('%y/%m/%d') ,owner_account_mile_changes_path(@owner_account , :date => changes.created_at.strftime('%Y-%m-%d') ) )%></td>
  	<td><%= changes.reason %></td>
   	<td align=right><%= changes.mile if changes.mile && changes.mile > 0%></td>
  	<td align=right><%= changes.mile if changes.mile && changes.mile <= 0%></td>
  	<td><%= to_note_str changes.note %></td>
  	<td align=center><%= raw changes.application_url ? url2link(changes.application_url,'●') : '' %></td>
  	<td align=center><%= raw changes.ground_url ? url2link(changes.ground_url,'●') :''%></td>
  	<td><%= h changes.turn %></td>
<%   if controller.has_role?(:accountant) -%>
    <td><%= link_to '編集', edit_owner_account_mile_change_path(@owner_account , changes) %></td>
    <td><%= link_to '削除', owner_account_mile_change_path(@owner_account ,changes), :confirm => "マイル履歴１件を削除します。\nよろしいですか？", :method => :delete %></td>
<%   end %>
      </tr>
<% sum += changes.mile.to_i %>  
<% if changes.mile.to_i > 0 
     plus += changes.mile.to_i
   else
     minus += changes.mile.to_i
   end %>  
<% end %>
  <tr>
  <th colspan = 2>合計</th>
	
  <td align=right><%= plus %></td>
  <td align=right><%= minus %></td>
  <td>総計：<%= plus + minus %></td>
  </tr>
</tbody>
</table>
<br />
<% case @owner_account.owner_type 
  when 'Character' 
  %>
  <%= link_to '[ 個人詳細 ]', @owner_account.owner %>
  <%  @nation = @owner_account.owner.nation %> 
  <%= link_to '[ 国民一覧 ]', nation_characters_path(@nation) %>
<% 
  when 'Nation'
      @nation = @owner_account.owner
  %>
  <%= link_to '[ 藩国メニュー ]', @nation %>
<%
  when 'Organization'
%>
  <%= link_to '[組織一覧]' , associated_nations_path %>
<%
  end
%>

<%= link_to '[ 金庫番トップ ]' , facade_owner_accounts_path if has_role?(:accountant) %>

<% args = {}
   args.merge({params: params[:turn]}) if params[:turn]
   @link = link_to( 'マイル口座' , owner_account_mile_changes_path(owner_account_id: @owner_account , turn: params[:turn]) )

%>

app/views/mile_changes/new.html.erb
<h1>新規マイル出納伝票</h1>

<%= error_messages_for :mile_change %>

<%= form_for(@mile_change ) do |f| %>
  <%= render :partial => 'form' ,:locals => { :f => f }%>
      <%= f.submit "追加" %>
	  
<% end %>

<%= link_to 'Back', owner_account_path(params[:owner_account_id]) %>

app/views/mile_changes/show.html.erb
<% for changes in owner_account.mile_changes %>
<%= link_to 'Edit', edit_owner_account_mile_change_path(@mile_change) %> |
<%= link_to 'Back', owner_account_mile_changes_path %>
<% end  %>