config/routes.rb
Monju::Application.routes.draw do
  resources :troop_definitions do

    member do
      get :validation
      get :parse
      get :value_check_list
      get :diff_form
    end

  end

  resources :npc_name_list
  resources :object_definitions
  resources :common_definitions , controller: :object_definitions , type: 'CommonDefinition'

  resources :specifications do
    collection do
      post :move_position
    end


  end

  resources :organizations
  resources :knights
  resources :adventurers_guild
  resources :advance_bases
  resources :individual_knights
  resources :corporations
  resources :other_orgs
  resources :aces do
    collection do
      get :items
      get :items_for_wiki
    end


  end

  resources :roles
  resources :i_definitions

  resources :nations do
    collection do
      get :top
      get :associated   , :action => :associated_nations_list
    end
    member do
      get :miles
    end
    resources :characters
    resources :collection
    resources :idress_wearing_tables do

      member do
        post :edit
        get :copy
        get :restriction_check
        get :vcc_format
      end

    end
  end

#  resources :mile_changes
  resources :owner_accounts do
#    get :facade
    collection do
      get :facade
      get :update_form_parts
      get :confirm
    end
    member do
      get :update_owner_account_list
      post :process_edit
    end

    resources :cash_records do
      collection do
        get :import_form
        post :import_select_table
        post :move_position
      end
    end

    resources :weapon_registries do
      collection do
        post :move_position
      end
    end

    resources :object_registries do
      collection do
        post :move_position
        get :wiki_output
      end
    end

    resources :job_idresses
    resources :mile_changes
    resources :yggdrasills

    resources :command_resources

    resources :unit_registries do
      member do
        get :rebuild
        get :disable
      end
    end
  end

  resources :unit_registries

  resources :yggdrasills do
    member do
      post :move
    end
  end

  resources :characters do
    collection do
      get :bonus_list
      post :move_position
    end
    member do
      get :acquired_idresses
      post :append_acquired_idress
      delete :remove_acquired_idress
      get :edit_note_for_acquirement
      put :update_note_for_acquirement
    end
    resources :bonds
  end

  resources :modify_commands

  match 'owner_accounts/:owner_account_id/weapons' => 'weapons#index' , :as => :weapons
  match 'owner_accounts/:owner_account_id/modify_commands' => 'modify_commands#index' , :as => :owner_account_modify_commands

  match 'taigen/compile.:format' => 'taigen#compile', :defaults => {:format => 'js'}

  match 'search/command_resources.:format' => 'search#command_resources' , defaults: {format: :js}
  match ':controller/service.wsdl' => '#wsdl'
  match '/:controller(/:action(/:id))'

end

app/controllers/search_controller.rb
# -*- encoding: utf-8 -*-
require 'kconv'
class SearchController < ApplicationController

  def form
  end

  def result
    keyword = params[:keyword].chomp
    @results = {}
    case params[:target]
      when 'characters'
        case keyword
          when /\d{2}-(\d{5}|xxxxx)-(\d|a|x)./
            character = Character.where(character_no: keyword).first || Ace.where(character_no: keyword).first
            redirect_to character if character
          when /\d{5}-\d{2}/
            characters = Character.where('character_no like ?', '%' + keyword + '%')
            redirect_to characters[0] if characters[0]
            @results[:characters] = characters
          when /^根源力(：|\:)/
            @results[:characters] = search_by_originator(keyword)
          else
            keyword = '%'+keyword + '%'
            @results[:characters] = Character.where("character_no like ? or name like ?", keyword, keyword).sort_by { |c| c.character_no }
        end
      when 'cash'
        results = search_cash_records(keyword)
        @results[:cash_records] = results if results.size > 0
      when 'mile'
        results = search_mile_changes(keyword)
        @results[:mile_changes] = results if results.size > 0
      when 'results'
        results = ::Result.includes(:character).where("concat(event_name , '%' , magic_item , '%' , note) like ?", '%' + keyword + '%')
        results = results.select { |r| !r.character.nil? }
        @results[:results] = results.sort { |a, b|
          if a.event_name == b.event_name
            a.character.character_no <=> b.character.character_no
          else
            a.event_name <=> b.event_name
          end
        } if results.size > 0
      when 'idress'
        @results[:derived_job_idresses] = Job.where('name like ?', '%' + keyword + '%')
        job_idresses = JobIdress.all
        @results[:job_idresses] = job_idresses.select { |j| j.inspect_idresses =~ /#{keyword}/ }
        #(:all , :include => :acquired_idress).select{|i|i.acquired_idress.inspect_idresses}
        job4s = @results[:job_idresses].select { |j| j.idress_type == 'PlayerIdress' }
        acquirements = []
        for j4 in job4s
          acquirements += IdressAcquirement.where('job_idress_id = ?', j4)
        end
        @results[:acquirements] = acquirements if acquirements.size > 0
      when 'items'
#        raise params.to_yaml
        key = '%' + keyword + '%'
        @results[:items] = ObjectRegistry.
            group([:owner_account_id , :name]).
            where(["name like ? or note like ?" , key , key]).
            having('sum(number) > 0')

      when 'weapons'
        results = search_weapons(keyword)
        @results[:weapons] = results
      when 'command_resources'
        @results[:command_resources] = search_command_resources(keyword)
    end

  end

  def search_by_originator(keyword)
    keyword = sub_nums(keyword)
    result = if keyword =~ /根源力(：|\:)(\d+)(以上|以下)/
               threshould = $2.to_i
               characters = if $3 == '以上'
                              Character.all(:include => [:results, :used_results]).select { |ch|
                                (ch.originator = ch.sum_originator) >= threshould
                              }
                            else
                              Character.all.select { |ch|
                                (ch.originator = ch.sum_originator) <= threshould
                              }
                            end
               characters.sort_by { |ch| ch.character_no }
             else
               []
             end
    result
  end


  def send_for_download(format)
    output = render_to_string file: format, use_full_path: true, layout: false
    case params[:charset]
      when 'sjis'
        output = output.tosjis
    end
    send_data(output,
              :type => 'text/csv',
              :filename => "result.csv")
  end

  def result_by_csv
    @results = search_cash_records(params[:keyword].chomp)
    send_for_download('search/result_by_csv.csv.erb')
  end

  def mile_by_csv
    @results = search_mile_changes(params[:keyword].chomp)
    send_for_download('search/mile_by_csv.csv.erb')
  end

  def command_resources
    @command_resources = search_command_resources(params[:q])

    respond_to do |format|
      format.xml { render :xml => @command_resources }
      format.js { render :json => @command_resources,
                         only: [:name, :power, :tag, :command_resources],
                         include:
                             {owner_accounts:
                                  {
                                      only: [:number, :name]
                                  }
                             },
                         callback: params[:callback]
      }
    end
  end

  private

  def build_command_resource_hash(cr)
    result = {owner: {}}

    cr_hash = {}

    cr_hash = %w{name power tag}.inject({}) { |h, k|
      h[k.to_sym] = cr[k.to_sym];
      h
    }
    result[:command_resource] = cr_hash
    result[:owner][:name] = cr.owner_account.owner.name
    if cr.owner_account.owner_type == 'Character'
      result[:owner][:character_no] = cr.owner_account.owner.character_no
    end
    result
  end

  def search_cash_records(keyword)
    if keyword =~ /^\d+$/
      cash_results = CashRecord.includes(:owner_account).where("event_no like ? or turn = ?", '%' + keyword + '%', keyword)
    else
      keyword = '%'+keyword+'%'
      cash_results = CashRecord.includes(:owner_account).where("concat(event_no  ,'%', event_name ,'%' , note) like ?", keyword)
    end
    results =
        cash_results.select { |c| c.owner_account.owner_type == 'Nation' }.sort_by { |c|
          [c.owner_account.id, c.position]
        } + cash_results.select { |c| c.owner_account.owner_type != 'Nation' }.sort_by { |c|
          [c.owner_account.owner.type.to_s, c.owner_account.id, c.position]
        }
    results.uniq!
    return results
  end

  def search_mile_changes(keyword)
    miles = []
    case keyword
      when /^\-\d+$/
        miles += MileChange.find_all_by_mile(keyword, :include => :owner_account)
      when /^\d+$/
        miles += MileChange.includes(:owner_account).where('mile = ? or turn = ?', keyword, keyword)
    end
    wildcard =  '%'+keyword+'%'
    miles += MileChange.includes(:owner_account).where("concat(reason , '%' ,  note) like ? ", wildcard )
    miles.uniq!
    miles = miles.sort_by { |row| row.created_at }
    return miles
  end

  def search_weapons(keyword)
    @weapon_registries = WeaponRegistry.
        find_by_sql([<<-EOS, '%' + keyword + '%'])
select w.owner_account_id, sum(w.number) as number , w.name
 from weapon_registries w
 group by owner_account_id , name
 having w.name like ?
    EOS
  end

  def search_command_resources(keyword)
      with_wild_cards = '%' + keyword.html_safe + '%'
      CommandResourceDefinition.
          where('tag like ? or name like ?', with_wild_cards, with_wild_cards).
          includes(command_resources: [:owner_account]).uniq
  end

  def build_crd_hash(crds)
#    crds.
  end

end


app/helpers/search_helper.rb
# -*- encoding: utf-8 -*-
module SearchHelper 

  include NationsHelper

  def format_result(target)
    case target
    when Character
      link_to target.character_no + ':' + target.name + '＠' + target.nation.name +
        (@results[:characters] ? ':' + target.originator.to_s : '') , target

    when OwnerAccount
      link_to "#{target.number+'：' if target.number}#{target.name}" , target.owner
    end
  end

  def owner_type_string(owner_account)
    case owner_account.owner_type
    when 'Nation'
      case owner_account.owner.belong
      when :republic
        '共和国'
      when :empire
        '帝國'
      when :associated
        '準藩国'
      else
        ''
      end
    when 'Organization'
      _( owner_account.owner.type.to_s )
    else
      ''
    end
  end
end

app/views/search/_acquirements.erb
<b>職業４習得</b><br/>
<ul>
  <%   for acquirements in @results[:acquirements] %>
      <% acquired = acquirements.acquired_idress %>
      <li> <%= link_to acquirements.character.character_no  + ':' + acquirements.character.name ,acquirements.character %> ：
        <%= link_to "#{acquired.inspect_idresses}(#{acquired.owner_account.owner.name})" , owner_account_job_idress_path(acquired.owner_account , acquired) %> </li>
  <%   end %>
</ul>

app/views/search/_cash_records.erb
CSV形式でダウンロード:
<%= link_to '(Shift-JIS)' , :action=>:result_by_csv,:keyword => params[:keyword],:charset => :sjis
%>,<%=link_to '(UTF-8)' , :action=>:result_by_csv,:keyword => params[:keyword] %><br/>
<%  cols = [:fund , :resource , :food , :fuel , :amusement , :num_npc ]
    sums = Hash.new{|hash,key|hash[key]=0}
%>
<table border = 1>
  <tr>
    <th> 口座 </th>
    <th> 種別 </th>
    <th>Ev No</th>
    <th>イベント名</th>
    <th>詳細</th>
    <th>資金</th>
    <th>資源</th>
    <th>食料</th>
    <th>燃料</th>
    <th>生物資源</th>
    <th>猫・犬士</th>
    <th>ターン</th>
    <th>該当ページ</th>
  </tr>
  <%    for cash_record in results[:cash_records] %>
      <tr>
        <td><%= cash_record.owner_account.owner.name %> </td>
        <td><%= owner_type_string(cash_record.owner_account)
        %> </td>
        <td><%= cash_record.event_no == '' ?  raw( '&nbsp') : cash_record.event_no  %></td>
        <td><%=h cash_record.event_name %></td>
        <td><%=link_to_if cash_record.reference_url , "●" , cash_record.reference_url %></td>
        <% for col in cols %>
            <td align=right>   <%= h cash_record[col].to_i %> <% sums[col] += cash_record[col].to_i%> </td>
        <% end %>
        <td><%=h cash_record.turn %></td>
        <td><%= link_to '[財務表]' , owner_account_cash_records_path(cash_record.owner_account , :turn=>cash_record.turn) %>
      </tr>
  <%    end  %>
  <tr>
    <td colspan=5>合計</td>
    <% for col in cols %>
        <td align=right>   <%= h sums[col].to_i %></td>
    <% end %>
  </tr>
</table>

app/views/search/_characters.erb
<ul>
  <%    for result in results[:characters] %>
      <li> <%=format_result(result) %> </li>
  <%    end  %>
</ul>

app/views/search/_command_resources.erb
<ul>
  <% for cr in results[:command_resources] %>
      <li>
        <%= cr.to_form %> <br/><%= link_to_toggle_part(format('所有者:%d名',cr.owner_accounts.size) , cr.name   ) {
        controller.render_to_string(partial: "characters" , locals: {
                results: {characters: cr.owner_accounts.to_a.sort_by{|o|o.number.to_s}}
        }).html_safe
      }%>
      </li>
  <% end %>
</ul>

app/views/search/_derived_job_idresses.erb
<br/>
<b>派生職業アイドレス</b><br/>
<ul>
  <%   for job_idress in results[:derived_job_idresses] %>
      <li> <%= link_to job_idress.name , 'http://farem.s101.xrea.com/idresswiki/index.php?'+URI.escape(job_idress.name.toeuc) %> </li>
  <%   end %>
</ul>

app/views/search/_form.erb
<%= form_tag({controller: :search , action: :result}  , method: :get) do -%>

  キーワード：<%= text_field_tag :keyword ,nil , :size => 40%> 
<%= submit_tag '文殊検索' ,:value => nil , :name => nil %><br/>
  <label for='target_characters'><%= radio_button_tag :target , :characters ,true %> キャラクター</label>
  <label for='target_cash'><%= radio_button_tag :target , :cash ,false %> 財務表 </label>
  <label for='target_mile'><%= radio_button_tag :target , :mile ,false %> マイル </label>
  <label for='target_results'><%= radio_button_tag :target , :results ,false %> リザルト </label><br/>
  <label for='target_idress'><%= radio_button_tag :target , :idress ,false %> 職業アイドレス </label>
  <label for='target_items'><%= radio_button_tag :target , :items ,false %> アイテム </label>
  <label for='target_weapons'><%= radio_button_tag :target , :weapons ,false %> 兵器 </label>
  <label for='target_command_resources'><%= radio_button_tag :target , :command_resources ,false %> コマンドリソース </label>
<% end  %>

app/views/search/_items.erb
<b>アイテム</b><br/>
<table border=1>
  <tr>
    <th> アイテム名 </th> <th> 備考 </th><th> 所有者 </th><th> 使用履歴 </th><th> 所持数 </th>
  </tr>

  <%= registries = [] %>
  <%
     rows_hash = results[:items].group_by(&:name)
     for name in rows_hash.keys.sort_by{|key|
       delegate = rows_hash[key].min{|a , b| a.created_at <=> b.created_at}
       delegate.object_definition ? delegate.object_definition.hurigana.to_s : ''
     }
       registries = rows_hash[name]
       by_characters = registries.group_by(&:owner_account)
  %>
      <tr>
        <td rowspan=<%= by_characters.keys.size %> >
          <%= link_to name , :controller => :object_definitions , :action => :owners_by_name , :name => name %>
          <%= link_to '[図鑑]' ,'http://www35.atwiki.jp/marsdaybreaker/?page=' + URI.encode(name) %>
        </td>
        <%     for owner_account_id in by_characters.keys %>
            <td><%= got_items(by_characters[owner_account_id]) %></td>
            <td><%= link_to OwnerAccount.find(owner_account_id).owner.name ,owner_account_object_registries_path(owner_account_id)%> </td>
            <td><%= used_items(by_characters[owner_account_id])%></td>
            <td><%=by_characters[owner_account_id].sum{|o| o.number.to_i }%></td>
            </tr>
            <tr>
        <%     end %>
  <% end %>
  </tr>
</table>

app/views/search/_job_idresses.erb
<b>アイドレス保有</b><br/>
<ul>
  <%   for job_idress in @results[:job_idresses] %>
      <li> <%= link_to job_idress.owner_account.owner.name ,job_idress.owner_account.owner %> ： <%= link_to job_idress.inspect_idresses , owner_account_job_idress_path(job_idress.owner_account , job_idress) %> </li>
  <%   end %>
</ul>

app/views/search/_mile_changes.erb
CSV形式でダウンロード:
<%= link_to '(Shift-JIS)', :action => :mile_by_csv, :keyword => params[:keyword], :charset => :sjis %>,
<%= link_to '(UTF-8)',     :action => :mile_by_csv, :keyword => params[:keyword] %><br/>
<table border=1>
  <tr>
    <th rowspan="2">所属</th>
    <th rowspan="2">番号</th>
    <th rowspan="2">口座名義</th>
    <th rowspan="2">事由</th>
    <th colspan="2">マイル</th>
    <th rowspan="2">申請</th>
    <th rowspan="2">根拠</th>
    <th rowspan="2">備考</th>
    <th rowspan="2">ターン</th>
    <th rowspan="2">登録日時</th>
  </tr>
  <tr>
    <th>収入</th>
    <th>支出</th>
  </tr>
  <% for row in results[:mile_changes] %>
      <tr>
        <td>
          <%=  row.owner_account.nation.name %>
        </td>
        <td>
          <%=   case row.owner_account.owner_type
                  when 'Character'
                    row.owner_account.owner.character_no
                  when 'Nation'
                    row.owner_account.owner.id
                  else
                    ''
                end -%>
        </td>
        <td> <%= row.owner_account.owner.name %> </td>
        <td> <%= row.reason %> </td>
        <td align=right> <%= row.mile if row.mile > 0 %> </td>
        <td align=right> <%= row.mile if row.mile < 0 %> </td>
        <td> <%= url2link(row.application_url , '●') %> </td>
        <td> <%= url2link(row.ground_url  , '●' ) %> </td>
        <td> <%= to_note_str row.note %> </td>
        <td> <%= row.turn %> </td>
        <td> <%= row.created_at.strftime('%y%m%d %H:%M') %> </td>
      </tr>
  <% end %>
</table>

app/views/search/_results.erb
<table border=1>
  <tr>
    <th>イベント名</th><th>国民番号</th><th width=100>キャラクター名</th><th>根源力</th><th>マジックアイテム</th><th>備考</th><th>リンク</th>
  </tr>
  <% for result in results[:results] %>
      <tr>
        <td> <%= result.event_name %> </td>
        <td> <%= result.character.character_no %> </td>
        <td> <%= result.character.name %> </td>
        <td align=right> <%= result.originator %> </td>
        <td> <%= raw result.magic_item %> </td>
        <td> <%= raw result.note %> </td>
        <td> <%= link_to '根源力表',:controller => :nations , :action => :format ,:id => result.character.nation ,:anchor => result.character.character_no  %> </td>
      </tr>
  <% end %>
</table>

app/views/search/_weapons.erb
<%
   result_hash = results[:weapons].group_by(&:name )
%>
<br/>
<% for key in result_hash.keys.sort %>
    <br/>
    <b> <%= key %> </b>
    <ul>
      <% for result in result_hash[key] %>
          <li>
            <%= link_to result.owner_account.owner.name , weapons_path(result.owner_account) %> ：
            <%= result.number %> ： <%= link_to '[履歴]' , owner_account_weapon_registries_path(result.owner_account , :name => key)  %>
          </li>
      <% end %>
    </ul>
<% end %>

app/views/search/form.html.erb
<h1>検索</h1>

<%= render :partial => 'form' %>

<h2>使い方</h2>
<p>
 文殊内のデータについてキーワード検索を行います。キーワードは一つだけ指定できます。
</p>
<dl>
  <dt><b> キャラクター検索 </b> </dt>
  <dd> 国民番号・国民名の一部一致検索を行います。<br/>
  国民番号を全て入力('2桁-5桁-2桁'数字の形式)した場合、一致するキャラクターがあれば、直接そのキャラの詳細ページを表示します。<br/>
  国民番号は全て半角数字と半角ハイフン('-')でなければなりません。</dd>
  
  <dt><b>  財務表検索  </b> </dt>
  <dd> 財務表の項目のうち、イベント番号・事由・備考欄から、キーワードを含むものを全て表示します。<br/>
     数字のみを入力した場合は、ターンとイベント番号が検索条件となります。</dd>
  
  <dt><b>  マイル検索  </b> </dt>
  <dd> マイル変動の項目のうち、事由・備考欄からキーワードを含むものを全て表示します。<br/>
  　キーワードが半角数字のみ（及び負符号）だった場合、上記に加え、マイル変動およびターン数も検索条件に含みます。</dd>
  <dt><b>  リザルト検索  </b> </dt>
  <dd> イベント名・マジックアイテム・備考欄のうち、キーワードを含むものを全て表示します。</dd>
  
  <dt><b>  職業アイドレス </b> </dt>
  <dd> アイドレス名にキーワードを含むものを表示します。<br/>
    職業４アイドレスが該当した場合は、それを習得した人も表示します。</dd>
  
</dl>
<% @link = '' %>

app/views/search/result.html.erb
<h1>検索結果</h1>

<b>検索対象：<%=  {'characters' => 'キャラクター','cash' => '財務表' , 
                 'results' => 'リザルト','mile' => 'マイル', 
                 'items' => 'アイテム' , 'weapons' => '兵器' ,
                 'command_resource' => 'コマンドリソース'}[params[:target]] %> </b><br/>
<%
  count = 0
  for key in [:characters , :cash_records , :mile_changes ,:results,:derived_job_idresses , :job_idresses , :acquirements ,:weapons , :command_resources]
    count += @results[key].size if @results[key]
  end

  if @results[:items]
    by_object_definition_id = @results[:items].group_by(&:object_definition_id)
    for object_definition_id in by_object_definition_id.keys
      count += by_object_definition_id[object_definition_id].group_by(&:owner_account_id).size
    end
  end
  %>
  <b>該当数：</b><%= count %>件<br/>

<% if count > 0 %>
<% if @results[:characters] %>
        <%= render partial: 'characters' , locals: {results: @results} %>
<% end #for :characters %>

<% if @results[:cash_records] %>
<%= render partial: 'cash_records' , locals: {results: @results} %>
<% end  %>

<% if @results[:mile_changes] %>
        <%= render partial: 'mile_changes' , locals:  {results: @results} %>
<% end %>
<%    if @results[:results] %>
        <%= render partial: 'results' , locals:  {results: @results} %>
<%   end # of :results %>
<% end %>
<% if @results[:derived_job_idresses]%>
    <%= render partial: 'derived_job_idresses' , locals:  {results: @results} %>
<% end %>
<% if @results[:job_idresses]%>
    <%= render partial: 'job_idresses' , locals:  {results: @results} %>
<% end %>
<% if @results[:acquirements]%>
    <%= render partial: 'acquirements' , locals:  {results: @results} %>
<% end %>
<%   if @results[:items]%>
    <%= render partial: 'items' , locals:  {results: @results} %>
<%   end # of :items %>
<% if @results[:weapons] %>
    <%= render partial: 'weapons' , locals:  {results: @results} %>
<% end  %>
<% if @results[:command_resources] %>
    <%= render partial: 'command_resources' , locals:  {results: @results} %>
<% end  %>

<% @link = link_to '検索結果' ,:action => :result , :keyword => params[:keyword] , :target => params[:target] %>

app/views/search/result_by_csv.csv.erb
口座,種別,Ev No,イベント名,詳細,資金,資源,食料,燃料,生物資源,猫・犬士,ターン,該当ページ
<% for cash_record in @results -%>
<%= cash_record.owner_account.owner.name 
-%>,<%= owner_type_string(cash_record.owner_account)
-%>,<%= cash_record.event_no == '' ?  '' : cash_record.event_no  
-%>,<%= cash_record.event_name 
-%>,<%= cash_record.reference_url 
-%><% for col in  [:fund , :resource , :food , :fuel , :amusement , :num_npc ]
-%>,<%= cash_record[col].to_i -%>
<% end -%>,<%=h cash_record.turn 
-%>,<%= owner_account_cash_records_url(cash_record.owner_account , :turn=>cash_record.turn) %>
<% end %>