config/routes.rb
Monju::Application.routes.draw do
  resources :troop_definitions do

    member do
      get :validation
      get :parse
      get :value_check_list
      get :diff_form
    end

  end

  resources :npc_name_list
  resources :object_definitions
  resources :common_definitions , controller: :object_definitions , type: 'CommonDefinition'

  resources :specifications do
    collection do
      post :move_position
    end


  end

  resources :organizations
  resources :knights
  resources :adventurers_guild
  resources :advance_bases
  resources :individual_knights
  resources :corporations
  resources :other_orgs
  resources :aces do
    collection do
      get :items
      get :items_for_wiki
    end


  end

  resources :roles
  resources :i_definitions

  resources :nations do
    collection do
      get :top
      get :associated   , :action => :associated_nations_list
    end
    member do
      get :miles
    end
    resources :characters
    resources :collection
    resources :idress_wearing_tables do

      member do
        post :edit
        get :copy
        get :restriction_check
        get :vcc_format
      end

    end
  end

#  resources :mile_changes
  resources :owner_accounts do
#    get :facade
    collection do
      get :facade
      get :update_form_parts
      get :confirm
    end
    member do
      get :update_owner_account_list
      post :process_edit
    end

    resources :cash_records do
      collection do
        get :import_form
        post :import_select_table
        post :move_position
      end
    end

    resources :weapon_registries do
      collection do
        post :move_position
      end
    end

    resources :object_registries do
      collection do
        post :move_position
        get :wiki_output
      end
    end

    resources :job_idresses
    resources :mile_changes
    resources :yggdrasills

    resources :command_resources

    resources :unit_registries do
      member do
        get :rebuild
        get :disable
      end
    end
  end

  resources :unit_registries

  resources :yggdrasills do
    member do
      post :move
    end
  end

  resources :characters do
    collection do
      get :bonus_list
      post :move_position
    end
    member do
      get :acquired_idresses
      post :append_acquired_idress
      delete :remove_acquired_idress
      get :edit_note_for_acquirement
      put :update_note_for_acquirement
    end
    resources :bonds
  end

  resources :modify_commands

  match 'owner_accounts/:owner_account_id/weapons' => 'weapons#index' , :as => :weapons
  match 'owner_accounts/:owner_account_id/modify_commands' => 'modify_commands#index' , :as => :owner_account_modify_commands

  match 'taigen/compile.:format' => 'taigen#compile', :defaults => {:format => 'js'}

  match 'search/command_resources.:format' => 'search#command_resources' , defaults: {format: :js}
  match ':controller/service.wsdl' => '#wsdl'
  match '/:controller(/:action(/:id))'

end

app/models/object_registry.rb
# -*- encoding: utf-8 -*-
class ObjectRegistry < ActiveRecord::Base
  attr_accessible :name , :number , :note , :position , :hq , :owner_account_id , :object_definition_id

  belongs_to :owner_account
  belongs_to :object_definition

  acts_as_list :scope => :owner_account_id
  
  before_save :update_definition_ref
  before_validation :normalize_colon

  validates_associated :owner_account

  def update_definition_ref
    self.object_definition = ObjectDefinition.find_by_name(self.name.strip)
  end
  
  def normalize_colon
    self.hq.gsub!('：',':') if hq
    self.hq.gsub!(/:\s*/,': ') if hq
  end
  
  def validate
    begin
      result = hq_hash
      if result != nil && result.class != Hash
        errors.add(:hq,'HQの書式が正しくありません。”修正対象：修正値”の形で各行に列記してください。'+result.inspect)
      end
    rescue
      errors.add(:hq, 'HQの書式が正しくありません。”修正対象：修正値”の形で各行に列記してください。'+result.inspect)
    end
  end
  
  def hq_hash
    return nil if hq.nil?
#    YAML.load('{' + self.hq + '}')
    result = YAML.load(self.hq.strip )
    result = nil if result == false
    result
  end


  private
  def num_of_current
    self.owner_account.num_of_property(self.name)
  end

  around_save do |record , block|
    before_flag = num_of_current == 0
    block.call
    record.owner_account.reload
    after_flag = num_of_current == 0

    if (before_flag != after_flag)
      if  (ygg = record.owner_account.yggdrasills.find_by_name(record.name))
        ygg.rebuild_command_resources
      elsif (crd = CommandResourceDefinition.find_by_name(record.name))
        if (cr = record.owner_account.command_resources.where('command_resource_definitions.name = ?' , record.name ).first )
          cr.available = (num_of_current > 0 )
          cr.save
        end
      end
    end
    true
  end
end

app/controllers/object_registries_controller.rb
# -*- encoding: utf-8 -*-
class ObjectRegistriesController < ApplicationController
  cache_sweeper :modify_sweeper , :only => [:create , :destroy , :update]

  requires_role :item_officer , :only => [:create , :update  , :destroy ,:new , :edit]
  set_login_filter

  include RowMover
  movable_row :child => :object_registry , :parent => :owner_account
  # GET /object_registries
  # GET /object_registries.xml
  def index
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @object_registries = @owner_account.object_registries.sort_by{|obr| 
        [(obr.object_definition ? obr.object_definition.hurigana.to_s : '' ),
          obr.note =~ /^アイドレス開始/o ? '00' : obr.note 
        ]
      }
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @object_registries }
    end
  end

  # GET /object_registries/1
  # GET /object_registries/1.xml
  def show
    @object_registry = ObjectRegistry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @object_registry }
    end
  end

  # GET /object_registries/new
  # GET /object_registries/new.xml
  def new
    @object_registry = ObjectRegistry.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @object_registry }
    end
  end

  # GET /object_registries/1/edit
  def edit
    @object_registry = ObjectRegistry.find(params[:id])
  end

  # POST /object_registries
  # POST /object_registries.xml
  def create
    @object_registry = ObjectRegistry.new(params[:object_registry])
    @object_registry.owner_account_id = params[:owner_account_id]
    respond_to do |format|
      if @object_registry.save
        flash[:notice] = '登録しました。'
        flash[:warning] = 'アイテム変動数が空欄です。間違っていませんか？' if @object_registry.number.nil?
        format.html { redirect_to(owner_account_object_registries_path(params[:owner_account_id])) }
        format.xml  { render :xml => @object_registry, :status => :created, :location => @object_registry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @object_registry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /object_registries/1
  # PUT /object_registries/1.xml
  def update
    @object_registry = ObjectRegistry.find(params[:id])

    respond_to do |format|
      if @object_registry.update_attributes(params[:object_registry])
        flash[:notice] = '編集しました。'
        flash[:warning] = 'アイテム変動数が空欄です。間違っていませんか？' if @object_registry.number.nil?
        format.html { redirect_to(owner_account_object_registries_path(params[:owner_account_id])) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @object_registry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /object_registries/1
  # DELETE /object_registries/1.xml
  def destroy
    @object_registry = ObjectRegistry.find(params[:id])
    @object_registry.destroy

    respond_to do |format|
      format.html { redirect_to(owner_account_object_registries_path(params[:owner_account_id])) }
      format.xml  { head :ok }
    end
  end
  
  def wiki_output
    @owner_account = OwnerAccount.find(params[:owner_account_id])
    @name = URI.unescape(params[:name])
    @registries = @owner_account.object_registries.select{|r| r[:name] == @name}
  end
end

app/helpers/object_registries_helper.rb
module ObjectRegistriesHelper
  include NationsHelper
end

app/views/object_registries/_form.erb
  <p>
    <b>名称</b><br />
    <%= f.text_field :name ,:size => 80 %>
  </p>

  <p>
    <b>数</b><br />
    <%= f.text_field :number ,:size => 20 %>
  </p>

  <p>
    <b>備考</b><br />
    <%= f.text_area :note ,:cols => 80 , :rows => 10%>
  </p>

  <p>
    <b>HQ</b><br />
    <%= f.text_area :hq ,:cols => 80 , :rows => 4 , :cols => 30%>
  </p>

<b>HQボーナスの定義方法</b><br/>
”ボーナス対象：修正値”の書式で、各行に列記します。<br/>
例：白兵+1、近距離+2の場合
--- 
<pre>
白兵：1
近距離：2
</pre>
---- <br/><br/>

数値は半角で入力してください。<br/>
コロン(':'）は全角・半角どちらでも結構です。<br/>
また、コロンの直後に半角空白があっても構いません。

app/views/object_registries/_group.erb
  <tr>
    <td> <%= owned_object[:name] %> <%= link_to('[図鑑]',zukan_url(owned_object[:name]) )%></td>
    <td> <%= owned_object[:number] -%> </td>
    <td>
<% if owned_object[:number] > 0 && owned_object[:definition] && owned_object[:definition].specialties.size > 0 -%>
        (
<%   for sp in owned_object[:definition].specialties -%>
<%=    (sp.effects.map{|ef| 
            value = ef[:value]
            value += owned_object[:hq][ef[:target]] if owned_object[:hq] &&owned_object[:hq][ef[:target]]
            "#{ef[:target]}:#{sprintf('%+d',value * owned_object[:number])}" 
        }).join(',') %>
<%   end -%>
)
<% end -%>
   </td>
<% if has_role? :item_officer %>
   <td>
     <%=   link_to '[wiki書式]' , wiki_output_owner_account_object_registries_path(owner_account , :name => URI.escape(owned_object[:name])) %>
   </td>
<% end  %>
 </tr>

app/views/object_registries/_object_registry.erb
<% if has_role?(:item_officer) %>
    <td> <%= radio_button_tag 'target_row' , object_registry.id ,selected , :onClick => "row_radio_clicked(#{object_registry.position});"%> </td>
<% end  %>
    <td><%=link_to object_registry.name , :controller => :object_definitions , :action => :owners_by_name , :name => object_registry.name %></td>
    <td><%=object_registry.number if object_registry.number %></td>
    <td><%= raw lf2br(url2link(object_registry.note , '[参照]')) %></td>
    <td><%= raw object_registry.object_definition ? link_to('[定義]',owner_account_object_registry_path(object_registry.owner_account , object_registry.object_definition)) : '未定義' +
             (has_role?(:item_officer) ? link_to('（新規登録）' , new_object_definition_path(:name => object_registry.name)  ): '' )%></td>
           <td> <%= (hq = object_registry.hq_hash).class == Hash ? hq.inspect : ''  %> </td>
    <td><%= link_to '詳細', owner_account_object_registry_path(params[:owner_account_id],object_registry[:id]) %></td>
<% if has_role?(:item_officer) -%>
    <td><%= link_to '編集', edit_owner_account_object_registry_path(params[:owner_account_id],object_registry[:id]) %></td>
    <td><%= link_to '削除', owner_account_object_registry_path(params[:owner_account_id],object_registry[:id]), 
              :confirm => "#{object_registry.name}の登録を削除します。よろしいですか？", :method => :delete %></td>
<% end -%>

app/views/object_registries/edit.html.erb
<h1>アイテム登録履歴の編集</h1>

<%= error_messages_for :object_registry %>

<%= form_for(@object_registry,  :url => owner_account_object_registry_path(params[:owner_account_id] ,@object_registry[:id])) do |f| %>
  <%= render :partial => 'form',:locals => {:f => f} %>
  <p>
    <%= f.submit "更新" %>
  </p>
<% end %>

<%= link_to '詳細', owner_account_object_registry_path(params[:owner_account_id] ,@object_registry[:id]) %> |
<%= link_to '戻る', owner_account_object_registries_path(params[:owner_account_id]) %>

<% @link = link_to 'アイテム履歴編集' %>

app/views/object_registries/index.html.erb
<%= render :partial => 'shared/move_position_func', 
    :locals => {:controller => "owner_accounts/#{@owner_account.id}/object_registries" ,
                :length => @owner_account.object_registries.size } %>
<h1><%= @owner_account.owner.name %> 所有アイテム等管理</h1>

<h2> 現在所持数 </h2>
<p>
<table border=1>
  <tr>
    <th>名称</th> <th>所持数</th> <th>修正など</th><% if has_role?(:item_officer) %><th> wiki書式 </th> <% end %>
  </tr>  

<% owned_objects = []
   @owner_account.object_registries.owned_objects.select{|obj| obj[:number] > 0}.each do |owned_object| %>
  <%= render :partial => 'group' , :locals => {:owner_account => @owner_account , :owned_object => owned_object} %>
<% end %>
</table>

<h2> <%= link_to_function  '消費済みアイテム' ,"new Effect.toggle('consumed' , 'slide' , {duration:0.3})" %></h2>
<div id='consumed' style="overflow: visible; display: none;">
<table border=1 >
  <tr>
    <th>名称</th> <th>所持数</th> <th>修正など</th><% if has_role?(:item_officer) %><th> wiki書式 </th> <% end %>
  </tr>  
<% @owner_account.object_registries.owned_objects.select{|obj| obj[:number] == 0}.each do |owned_object| %>
  <%= render :partial => 'group' , :locals => {:owner_account => @owner_account , :owned_object => owned_object} %>
<% end %>
</table>
</div>
</p>

<hr/>
<h2>登録履歴</h2>
<%= link_to( '[新規登録]', new_owner_account_object_registry_path(params[:owner_account_id]) ) if has_role?(:item_officer)%>
<table border=1>
  <tr>
    <%=  content_tag(:th) if has_role?(:item_officer) %>
    <th>名称</th>
    <th>数</th>
    <th>備考</th>
    <th>定義</th>
    <th>HQ</th>
  </tr>

<% for object_registry in @object_registries %>
  <tr id="row_<%=object_registry.position %>" >
    <%= render :partial => 'object_registry' , :locals => {:object_registry => object_registry ,:selected => false} %>
  </tr>
<% end %>
</table>
<% if has_role?(:item_officer)%>
<%= move_button :up %> 
<%= move_button :down %>
<% end %>

<br /><br />

<%=
case @owner_account.owner
when Nation , Character
  link_to('[藩国別一覧]' , :controller => :nations ,  :action => :items_by_nation , :id =>  @owner_account.nation )
when Ace
  link_to('[所有者詳細]' , @owner_account.owner) + ' | ' + link_to('[ACE一覧]' , aces_path)
else
  #do nothing
end
-%>
<% @link = link_to '所有アイテム等一覧' %>

app/views/object_registries/new.html.erb
<h1>所有アイテム等の新規登録</h1>

<%= error_messages_for :object_registry %>

<%= form_for(@object_registry , :url => owner_account_object_registries_path(params[:owner_account_id]) ) do |f| %>
  <%= render :partial =>'form', :locals => {:f => f} %>

  <p>
    <%= f.submit "登録" %>
  </p>
<% end %>

<%= link_to '戻る', owner_account_object_registries_path(params[:owner_account_id]) %>
<% @link = link_to 'アイテム履歴登録' %>

app/views/object_registries/show.html.erb
<p>
  <b>名称：</b>
  <%=h @object_registry.name %>
</p>
<p>
  <b>変動数：</b>
  <%=h @object_registry.number %>
</p>

<p>
  <b>備考:</b><br/>
  <%=to_note_str @object_registry.note %>
</p>


<%= link_to_if has_role?(:item_officer) ,  '編集', edit_owner_account_object_registry_path(params[:owner_account_id],@object_registry[:id]) %> |
<%= link_to '戻る', owner_account_object_registries_path(params[:owner_account_id]) %> 
<% @link = link_to 'アイテム履歴詳細' %>

app/views/object_registries/wiki_output.erb
<h2>国別所有アイテム用書式 </h2>
<table border=1>
  <tr>
    <td> <%= URI.unescape(params[:name]) %></td>
      <td> <%= got_items(@registries) %> </td>
    <% if @owner_account.owner.class != Nation %>
    <td> <%= @owner_account.owner.name %> </td>
    <% end %>
    <td> <%= used_items(@registries) %> </td>
    <td> <%= @registries.sum{|o| o.number.to_i } %> </td>
  </tr>
</table>
<br/>
<textarea rows=5 cols=100>
|[[<%= URI.unescape(params[:name]) %>]]|<%=  got_items_for_wiki(@registries) -%>
<% if @owner_account.owner.class != Nation -%>
|<%= @owner_account.owner.name -%>
<% end -%>
|<%= used_items_for_wiki(@registries) -%>
|<%= @registries.sum{|o| o.number.to_i } %>|
</textarea>

<h2> アイテム別所有者一覧用書式</h2>
<table border=1>
  <tr>
    <td> <%= @owner_account.nation === Nation ? @owner_account.nation.name : 'ACE' %></td>
      <td> <%= got_items(@registries) %> </td>
    <td> <%= @owner_account.owner.name %> </td>
    <td> <%= used_items(@registries) %> </td>
    <td> <%= @registries.sum{|o| o.number.to_i } %> </td>
  </tr>
</table>
<br/>
<textarea rows=5 cols=100>
|[[<%= @owner_account.nation === Nation ? @owner_account.nation.name : 'ACE>ACE所持アイテムリスト'%>]]|<%=  got_items_for_wiki(@registries) -%>
|<%= @owner_account.owner.name -%>
|<%= used_items_for_wiki(@registries) -%>
|<%= @registries.sum{|o| o.number.to_i } %>|
</textarea>
<br/>
＃行頭のアイテム名列・ないし国名列は、必要に応じて"|~|"に置き換えて下さい。

<% @link = link_to 'wiki書式出力' , :name => params[:name] %>