config/routes.rb
Monju::Application.routes.draw do
  resources :troop_definitions do

    member do
      get :validation
      get :parse
      get :value_check_list
      get :diff_form
    end

  end

  resources :npc_name_list
  resources :object_definitions
  resources :common_definitions , controller: :object_definitions , type: 'CommonDefinition'

  resources :specifications do
    collection do
      post :move_position
    end


  end

  resources :organizations
  resources :knights
  resources :adventurers_guild
  resources :advance_bases
  resources :individual_knights
  resources :corporations
  resources :other_orgs
  resources :aces do
    collection do
      get :items
      get :items_for_wiki
    end


  end

  resources :roles
  resources :i_definitions

  resources :nations do
    collection do
      get :top
      get :associated   , :action => :associated_nations_list
    end
    member do
      get :miles
    end
    resources :characters
    resources :collection
    resources :idress_wearing_tables do

      member do
        post :edit
        get :copy
        get :restriction_check
        get :vcc_format
      end

    end
  end

#  resources :mile_changes
  resources :owner_accounts do
#    get :facade
    collection do
      get :facade
      get :update_form_parts
      get :confirm
    end
    member do
      get :update_owner_account_list
      post :process_edit
    end

    resources :cash_records do
      collection do
        get :import_form
        post :import_select_table
        post :move_position
      end
    end

    resources :weapon_registries do
      collection do
        post :move_position
      end
    end

    resources :object_registries do
      collection do
        post :move_position
        get :wiki_output
      end
    end

    resources :job_idresses
    resources :mile_changes
    resources :yggdrasills

    resources :command_resources

    resources :unit_registries do
      member do
        get :rebuild
        get :disable
      end
    end
  end

  resources :unit_registries

  resources :yggdrasills do
    member do
      post :move
    end
  end

  resources :characters do
    collection do
      get :bonus_list
      post :move_position
    end
    member do
      get :acquired_idresses
      post :append_acquired_idress
      delete :remove_acquired_idress
      get :edit_note_for_acquirement
      put :update_note_for_acquirement
    end
    resources :bonds
  end

  resources :modify_commands

  match 'owner_accounts/:owner_account_id/weapons' => 'weapons#index' , :as => :weapons
  match 'owner_accounts/:owner_account_id/modify_commands' => 'modify_commands#index' , :as => :owner_account_modify_commands

  match 'taigen/compile.:format' => 'taigen#compile', :defaults => {:format => 'js'}

  match 'search/command_resources.:format' => 'search#command_resources' , defaults: {format: :js}
  match ':controller/service.wsdl' => '#wsdl'
  match '/:controller(/:action(/:id))'

end

app/models/character.rb
# -*- encoding: utf-8 -*-

class Character < ActiveRecord::Base
  attr_accessible :name , :originator , :nation_id , :job_idress_id , :character_no , :personal_idress_id ,
                  :qualification , :phy , :str , :dur , :chr , :agi , :dex  , :sen , :edu , :luc ,
                  :intention , :player_name , :ar , :status , :race_type , :note , :gender


  include Calcuratable
  belongs_to :nation
  belongs_to :job_idress
  
  belongs_to :personal_idress, 
  :class_name => "JobIdress",
  :foreign_key => "personal_idress_id"
  
  has_many :results , :order => "position"
  has_many :used_results ,:order => "id"
  has_many :idress_acquirements
  has_many :acquired_idresses , :through => :idress_acquirements

  has_one :owner_account , :as => :owner
  has_many :bonds

  owner_factory = OwnerAccountFactory.new(:character_no)
  after_create owner_factory
  after_update owner_factory
  
  def ability(col) ## override from Culcuratable
    if Job::Abilities.include? col
      val = self.job_idress[col]
      val +=self.personal_idress[col] if self.personal_idress
      val
    else
      nil
    end
  end
  
  def sum_originator
    result = sum_proper_originator
#    result += personal_idress.originator.to_i if personal_idress
    result
  end
  
  def sum_proper_originator
    sum_results + sum_initials + sum_used_results
  end
  
  def sum_results
    result = 0
    for r in results
      result += r.originator.to_i unless r.not_yet
    end
    result
  end
  
  def sum_initials
    result = 0
    for ur in used_results
      result += ur.initial.to_i
    end
    result
  end
  
  def sum_used_results
    result = 0
    for ur in used_results
      result +=  ur.result.to_i
    end
    result
  end
  
  def sum_ability(col)
    if Job::Abilities.include? col
      val = 0
      val = self.job_idress[col] if self.job_idress
      val +=self.personal_idress[col] if self.personal_idress
      val += self.attributes[col.to_s] if self.attributes[col.to_s]
      val
    else
      nil
    end
  end
   before_update :set_nil_if_zero
  
  def set_nil_if_zero
    [:phy , :str , :dur , :chr , :agi , :dex , :sen , :edu , :luc , :ar].each{|a|
      self[a]= nil if self.send(a.to_s)==0
    }
    return true
  end
  
  def create_owner_account
    unless owner_account 
      account = OwnerAccount.new
      account.character = self
      account.save
    end
  end
  
  def inspect_idresses
    self.job_idress ? self.job_idress.inspect_idresses : ''
  end

  def available_command_resources
    CommandResource.nested_availabilities(self.owner_account.id , self.nation.owner_account.id)
  end

  def extended_command_resources
    self.nation.owner_account.command_resources.extendable.collect{|cr|cr[:from] = self.nation.name ; cr}
  end

  def after_update
    owner_account.name = self.name self.owner_account.name != self.name
    owner_account.number = self.character_no if self.owner_account.number != self.character_no
    owner_account.save
  end

  def is_noble?
    !! (self.qualification =~ /藩王.級/)
  end
end

app/controllers/characters_controller.rb
# -*- encoding: utf-8 -*-
class CharactersController < ApplicationController
  cache_sweeper :modify_sweeper , 
     :only => [:create , :destroy , :update, 
               :new_result , :update_result, :destroy_result ,
               :new_used_result , :update_used_result , :destroy_used_result 
              ]

  #  before_filter :login_required , 
#  :only => [:create,:destroy, :insert_by_text, :edit , :update , 
#  :edit_result, :new_result , :update_result , :destroy_result,
#  :update_used_result , :new_used_result, :destroy_used_result]

  requires_role :herald , 
  :only => [:create,:destroy, :insert_by_text, :edit , :update , 
  :edit_result, :new_result , :update_result , :destroy_result,
  :update_used_result , :new_used_result, :destroy_used_result ,
  :move_position ,
  :acquired_idresses , :edit_note_for_acquirement , :update_note_for_acquirement ,
  :append_acquired_idress , :remove_acquired_idress 
  ]

  requires_role :monju_maintainer ,
    :only => [:acquired_idresses , :edit_note_for_acquirement ,
              :update_note_for_acquirement ,
              :append_acquired_idress , :remove_acquired_idress ]

  set_login_filter
  
  def index
    list
    #   render :action => 'list'
  end
  
  # GETs should be safe (see http://www.w3.org/2001/tag/doc/whenToUseGet.html)
#  verify :method => :post, :only => [ :create, :destroy_used_result , :destroy_result ,
#   ],
#  :redirect_to => { :action => :list }
  
  def list
    if params[:character_no]
      @characters = [Character.find_by_character_no(params[:character_no])]
    else
      @characters = Character.find(:all , 
                                   :conditions => ["nation_id = ?", params[:nation_id]]).sort_by{|c|c.character_no}
    end

    @characters.each{|ch| ch.originator = ch.sum_originator}
    respond_to do |format|
      format.html # list.html.erb
      format.xml  { render :xml => @characters }
      format.js { render :json => @characters , :callback => params[:callback] } 
    end
  end
  
  def find

    if params[:nation_id] 
      @characters = Character.find(:all , 
                                   :conditions => ["nation_id = ?", params[:nation_id]]).sort_by{|c|c.character_no}
    elsif params[:character_no]
      @characters = Character.find_by_character_no(params[:character_no])
    end
    
    respond_to do |format|
      format.html {render :template => 'list' }
      format.xml  { render :xml => @characters }
      format.js { render :json => @characters , :callback => params[:callback] } 
    end
  end
  
  def show
    if params[:character_no]
      @character = Character.find_by_character_no(params[:character_no])
    else
      @character = Character.find(params[:id])
    end
    if @character.nil? then
      
    end
    @character.originator = @character.sum_originator
    respond_to do |format|
      format.html # list.html.erb
      format.xml  { render :xml => @character }
      format.js { render :json => @characters , :callback => params[:callback] } 
    end
  end
  
  def new
    @character = Character.new
    @character.owner_account = OwnerAccount.new
    if params[:nation_id] then
      @character.nation = Nation.find(params[:nation_id].to_i)
    end
    @character
  end
  
  def create
    @character = Character.new(params[:character])
    if @character.save
      flash[:notice] = 'キャラクターを追加しました。'
      redirect_to nation_characters_path(@character.nation)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @character = Character.find(params[:id])
  end
  
  def edit_result
    @character = Character.find(params[:id])
  end
  
  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      flash[:notice] = 'キャラクター詳細を更新しました。'
      redirect_to nation_characters_path(@character.nation)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    ch = Character.find(params[:id])
    nation_id = ch.nation_id
    ch.destroy
    redirect_to nation_characters_path(nation_id)
 end
  
  
  def update_job_idress_list
    @nation = Nation.find(params[:nation_id])
    @owner_account = @nation.owner_account
    render(:layout => false)
  end
  
  def parse_text(text)
    rows = []
    records = []    
    for line in list
      record = {}
      line.strip!
      row = line.split(/\s+/).join(',')
      next if row.size == 0
      rows << row
      record = {}
      data = row.split(',')
      for col in [:character_no,:name, :originator ]
        record[col]=data.shift
      end
      record[:jobs] = data.shift.split(/[＋+]/)
      records << record
    end
    records
  end
  
  def find_job_idress(record)
    nation_id = record[:character_no][0..1]
    prepare_job_idresses(nation_id)
    
    for ji in @jis[nation_id]
      return ji if ji.is_this?(record[:jobs])
    end
    return nil
  end
  
  def prepare_job_idresses(nation_id)
    @jis = {} unless @jis
    @jis[nation_id] = JobIdress.find(:all,:conditions => "nation_id = #{nation_id}" ) unless @jis[nation_id]
  end
  
  def insert_form
    
  end
  
  def new_result
    @character = Character.find(params[:id])
    result = @character.results.create(params[:new_result])
    render :action=> 'edit_result' , :id=>params[:id]
  end
  
  def destroy_result
    result = ::Result.find(params[:id])
    character = result.character
    result.destroy
    
    redirect_to :action => 'edit_result' , :id=>character
  end
  
  def destroy_used_result
    UsedResult.find(params[:id]).destroy
    
    redirect_to :action => 'edit_result' , :id=>params[:character_id]
  end
  
  def update_result
    results = params[:result]
    flag = true
    
    ::Result.transaction do
      for r_key in results.keys
        result_record = ::Result.find(r_key)
        if result_record != results[r_key]
          flag = flag && result_record.update_attributes(results[r_key])
        end
        raise ActiveRecord::Rollback ,"A Result update failed." unless flag
      end
      if flag
        flash[:notice] = '根源力は更新されました'
        redirect_to :action => 'edit_result', :id => params[:id]
      else
        render :action => 'edit'
      end
    end
  end
  
  def update_used_result
    used_results = params[:used_result]
    flag = true
    UsedResult.transaction do
      for r_key in used_results.keys
        result_record = UsedResult.find(r_key)
        if result_record != used_results[r_key]
          flag = flag && result_record.update_attributes(used_results[r_key])
        end
        raise ActiveRecord::Rollback ,"A UsedResult update failed." unless flag
      end
      if flag
        flash[:notice] = '転用根源力は更新されました'
        redirect_to :action => 'edit_result', :id => params[:id]
      else
        render :action => 'edit'
      end
    end
  end
  
  def new_used_result
    @used_result = UsedResult.new
    if params[:id] then
      @used_result.character = Character.find(params[:id].to_i)
    end
    @used_result.update_attributes(params[:new_used_result])
    @used_result.save
    redirect_to :action => 'edit_result' , :id => params[:id]
  end

  include RowMover
  movable_row :child => :result , :parent => :character , :child_class => ::Result
  
  def auth_context_id
    return params[:nation_id] if params[:nation_id] 
    return Character.find(params[:character_id]).nation_id.to_s if params[:character_id]
    return Character.find(params[:id]).nation_id.to_s if params[:id]
    return params[:character][:nation_id] if params[:character]
    return false
  end
  
  def bonus_list
    if params[:nation_id]
      c_list = Character.find(:all , 
                              :conditions => ["nation_id = ?", params[:nation_id]])
    else
      c_list = Character.find(:all)
    end
    @characters = c_list.sort_by{|c|c.character_no}
  end
  def acquired_idresses
    @character = Character.find(params[:id] , :include => :acquired_idresses )
    @acquired_idresses = @character.acquired_idresses
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @acquired_idresses }
      format.js {render :json => @acquired_idresses , :callback => params[:callback] }
    end
  end
  
  def append_acquired_idress
    acquired_idress = JobIdress.find(params[:acquired_idress_id])
    @character = Character.find(params[:id])
    @character.acquired_idresses << acquired_idress
    redirect_to acquired_idresses_character_path(@character) , :character_id => params[:character_id]
  end
  
  def remove_acquired_idress
    character = Character.find(params[:id])
    acquired_idress = JobIdress.find(params[:acquired_idress_id])
    character.acquired_idresses.delete(acquired_idress)
    redirect_to acquired_idresses_character_path(params[:id])
  end
  
  def edit_note_for_acquirement
    @character = Character.find(params[:id])
    @idress_acquirement = IdressAcquirement.find(params[:idress_acquirement_id])
  end
  
  def update_note_for_acquirement
    @character = Character.find(params[:id])
    @idress_acquirement = IdressAcquirement.find(params[:idress_acquirement_id])
    @idress_acquirement.note = params[:idress_acquirement][:note]
    @idress_acquirement.save
    redirect_to acquired_idresses_character_path(params[:id])
  end
  private
  def insert_by_text
    @records = parse_text(params[:character_list])
    @ji_list = []
    Character.transaction do
      for rec in @records
        next unless rec
        ji = find_job_idress(rec)
        @ji_list << [rec,ji]
        character = Character.find(:first , :conditions => "character_no = #{rec[:character_no]}")
        character = Character.new unless character
        character.name = rec[:name]

app/helpers/characters_helper.rb
module CharactersHelper

  def originator_disp(ch)
    result = h ch.sum_originator 
    if ch.personal_idress && ch.personal_idress.originator.to_i > 0 
      result += sprintf("( %d + %d )",ch.sum_initials + ch.sum_used_results + ch.sum_results , ch.personal_idress.originator.to_i)
    end
    result
  end

end

app/views/characters/_result.erb
  <td>
    <%= radio_button_tag 'target_row' , result.id ,selected , :onClick => "row_radio_clicked(#{result.position});"%>
    <%= text_field "result", 'event_name', :size=>40 %>
  </td>
  <td>
    <%= text_field "result", 'originator' , :size=>6 %>
  </td>
  <td>
    <%= text_field "result", 'magic_item' , :size =>20 %>
  </td>
  <td>
    <%= text_field "result", 'url'  ,:size=>30 %>
  </td>
  <td>
    <%= text_field "result", 'note' ,:size=>30 %> 
  </td>
  <td>
    <%= check_box "result", 'not_yet' %> 
  </td>
  <td>
    <%= link_to '削除', { :action => 'destroy_result', :id => result }, :confirm => '削除します。よろしいですか？?', :method => :post %>
  </td>

app/views/characters/_result_edit.html.erb
<% @sum = 0 %>
<table>
<tr><th>イベント名</th><th> 根源力 </th><th> マジックアイテム</th><th> 参照URL </th><th> 備考 </th><th> 未提出 </th>
</tr>
<% result_set = @character.results.sort_by{|a| a.position }
for @result in result_set

%>
<tr id="row_<%=@result.position %>" >
  <td>
    <%= radio_button_tag 'target_row' , @result.id ,false , :onClick => "row_radio_clicked(#{@result.position});"%>
    <%= text_field "result[]", 'event_name', :size=>40 %>
  </td>
  <td>
    <%= text_field "result[]", 'originator' , :size=>6 %>
  </td>
  <td>
    <%= text_field "result[]", 'magic_item' , :size =>20 %>
  </td>
  <td>
    <%= text_field "result[]", 'url'  ,:size=>30 %>
  </td>
  <td>
    <%= text_field "result[]", 'note' ,:size=>30 %> 
  </td>
  <td>
    <%= check_box "result[]", 'not_yet' %> 
  </td>
  <td>
    <%= link_to '削除', { :action => 'destroy_result', :id => @result }, :confirm => '削除します。よろしいですか？?', :method => :post %>
  </td>
</tr>
<% @sum += @result.originator unless @result.not_yet %>
<% end %>
</table>

根源力小計：<%= @sum %> <br/>
根源力合計：<%= @character.sum_proper_originator  %>


app/views/characters/acquired_idresses.erb
<% @link = link_to '職業４アイドレス管理' , acquired_idresses_character_path(@character) %>
<table border=1>
<tr>
  <th>名称</th>
  <th>体格</th>
  <th>筋力</th>
  <th>耐久力</th>
  <th>外見</th>
  <th>敏捷</th>
  <th>器用</th>
  <th>感覚</th>
  <th>知識</th>
  <th>幸運</th>
  <th>備考</th>
</tr>
<% for acquirement in @character.idress_acquirements %>
<%   acquired_idress = acquirement.acquired_idress %>
<tr>
  <td><%= link_to acquired_idress.name ,owner_account_job_idress_path(acquired_idress.owner_account , acquired_idress) %> </td>
  <% for col in Job::Abilities %>
  <td> <%= acquired_idress[col]  %> </td>
  <% end %>
  <td> <%= to_note_str acquirement.note %> </td>
  <td> <%= link_to '[備考編集]' ,:action => :edit_note_for_acquirement,:id => @character , :idress_acquirement_id => acquirement %>
<%= link_to '[削除]' , {:action => :remove_acquired_idress,:id => @character , :acquired_idress_id => acquired_idress } ,
          :confirm => "#{acquired_idress.name}を習得リストから削除します。よろしいですか？" , :method => :delete %>
  </td>
</tr>
<% end %>
</table>
<br/>
<%
  job4s = JobIdress.find_all_by_idress_type('PlayerIdress',:order => :owner_account_id )
  job4_selection = options_for_select(job4s.map{|ji| ["#{ji.inspect_idresses} (#{ji.owner_account.owner.name})", ji.id]})
%>
<%= form_tag append_acquired_idress_character_path(@character)  do -%>
  <b>職業４一覧：</b><br/>
  <%= select_tag :acquired_idress_id , job4_selection , :size => 10%>
  <br/>
  <%= submit_tag '職業４習得'%>
<% end %>

app/views/characters/edit.html.erb
<% @link = link_to "根源力編集" %>
<% @nation_id = @character.nation_id %>
<h1>国民詳細編集</h1>

<%= form_for( @character , :url => nation_character_path(@nation_id ,  @character.id )  ) do %>
  <%= render :partial => 'form' %>
  <%= submit_tag '更新' %>
<% end %>

app/views/characters/edit_note_for_acquirement.erb
<% @link = link_to '職業４アイドレス管理' , acquired_idresses_character_path(@character) %>

<%= form_for :idress_acquirement , :url =>{
       :action => :update_note_for_acquirement , 
       :id => @character,
       :idress_acquirement_id => @idress_acquirement 
     } ,:html => {:method => :put } do |f|%>
<%= @idress_acquirement.acquired_idress.name %>習得についての備考：<br/>
  <%= f.text_area :note %>
     <br/>
     <%= submit_tag '更新' %>
<% end %>

app/views/characters/index.html.erb
<h1>国民一覧</h1>

<% if controller.has_role?(:herald)  %>
  <%= button_to '新規国民追加', new_nation_character_path(params[:nation_id]) , :method => :get %>
<% end %>

<table>
  <tr>
    <th>所属国</th> <th>国民番号</th> <th>キャラクター名</th> <th> </th> <th>根源力 </th> <th> </th> <th> マイル </th>
  </tr>
  
<% for character in @characters %>
  <tr>
    <td> <%= character.nation.short_name %></td>
    <td> <%= character.character_no %></td>
    <td> <%= character.name %> </td>
    <td> <%= character.status == '通常' ? '' : "&nbsp#{character.status}&nbsp".html_safe %> </td>
    <td align='right' > <%= character.sum_initials + character.sum_used_results + character.sum_results %></td>
    <td align='right' > 
    <%= sprintf(" + %d" ,  character.personal_idress.job4.originator )if character.personal_idress && character.personal_idress.job4.originator.to_i > 0 %></td>
    <td align='right' > <%= link_to character.owner_account.miles , owner_account_mile_changes_path(character.owner_account,:turn => 'last')%></td>
    <td><%= link_to '詳細', character%></td>
    <% if controller.has_role?(:herald)  %>
    <td><%= link_to '詳細編集', :action => 'edit', :id => character %></td>
    <td><%= link_to '根源力管理', :action => 'edit_result', :id => character %></td>
    <td><%= link_to '削除', character , :confirm => 'このキャラを削除しますか？', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>

</table>

<br />

<% @nation_id = params[:nation_id] %>

app/views/characters/insert_by_text.html.erb
<% @link = link_to "まとめて登録" %>
<h1>登録内容</h1>
<p>
<% 
  for @jil in @ji_list
  
%>
<%= sprintf("%s,%s,%s" , @jil[0][:name],@jil[1] ? @jil[1].name : 'nil' ,@jil[0][:jobs] ) %>    <br/>
<%
  end
%>
</p>
<%= link_to 'Show', :action => 'show', :id => @character %> |
<%= link_to 'Back', :action => 'list' %>

app/views/characters/show.html.erb
<% @link = link_to "国民詳細" %>
<p>
  <b>国民番号</b> <%=h @character.character_no %>
</p>
<p>
  <b>ＰＣ名:</b> <%=h @character.name%>
</p>
<p>
  <b>性別:</b> <%=h( {'male' => '男' , 'female' => '女' , 'undefined' => '未定義'}[@character.gender]) %>
</p>
<p>
  <b>プレイヤー名:</b> <%=h @character.player_name %>
</p>

<p>
  <b>人種:</b> <%=h @character.race_type %>
</p>

<p>
  <b>根源力:</b> <%=h @character.sum_originator %> 
  <% if @character.personal_idress && @character.personal_idress.job4.originator.to_i > 0 %>
    ( <%= @character.sum_proper_originator %> + <%= @character.personal_idress.job4.originator.to_i %> )
  <% end %>
</p>
<p>
  <b>所持資格:</b> <%=h @character.qualification%>
</p>
<p>
  <b>個人修正:</b><br/>
　体格： <%=h @character.phy %>
　筋力： <%=h @character.str %>
  耐久力： <%=h @character.dur %>
  外見： <%=h @character.chr %>
  敏捷： <%=h @character.agi %>
  器用： <%=h @character.dex %>
  感覚： <%=h @character.sen %>
  知識： <%=h @character.edu %>
  幸運： <%=h @character.luc %>
  AR： <%=h @character.ar%>
</p>
<p>
  <b>イベント参加意思:</b> <%=h @character.intention %>
</p>
<p>
  <b>ステータス</b> <%=h @character.status %>
</p>
<p>
  <b>特記事項：</b><br/>
<p style='margin-left:20px'><%=h @character.note %></p>
</p>

  <p><label for="character_player_idresses"> <b>個人保有アイドレス：</b></label>
<% if @character.owner_account.job_idresses.count == 0 %>
なし<br/>
<% else %>
  <br/>
<ul>
<%    for job_idress in @character.owner_account.job_idresses %>
  <li> <%= job_idress.inspect_idresses %> <%= '（職業４）' if job_idress.idress_type == 'PlayerIdress' %></li>
<% end %>
</ul>
<% end %>
<ul>
  <%= render :partial => 'shared/owner_account_menu' , :locals => {:owner_account => @character.owner_account } %>
</ul>
</p>
<p>
  <b>習得した職業４アイドレス：</b>
<% if @character.idress_acquirements.size == 0 %>
   なし <br/>
<% else %>
<ul>
  <% for acquired in @character.idress_acquirements.sort_by{|ac| ac.created_at } %>
    <li> <b><%= acquired.acquired_idress.name %>（<%= acquired.acquired_idress.owner_account.owner.name %>）：</b><br/>
    <%= to_note_str acquired.note %></li>
  <% end %>
</ul>
<% end %>
<ul>
  <li><%= link_to_if has_role?(:herald , :monju_maintainer) , '職業４アイドレス管理' , acquired_idresses_character_path(@character)%></li>
</ul>
  </p>
  <p>
<b>所持マイル：</b> <%= h @character.owner_account.sum(:mile) %> 
</p>
<ul>
  <li><%= link_to '[マイル口座]' , owner_account_mile_changes_path(@character.owner_account,:turn => 'last')%></li>
</ul>

<b>所有するアイテム等:</b> <%= link_to '[所有アイテム登録履歴]', owner_account_object_registries_path(@character.owner_account) %>
<ul>
<% @character.owner_account.object_registries.group_by(&:name).each do |name , object_group|  
  number  = object_group.sum{|o|o.number.to_i}%>
<% if number > 0 %>
<li><%= name %> : <%=  number -%>
<%   if number > 0 && object_group[0].object_definition && object_group[0].object_definition.specialties.size > 0 -%>
 (
<%     for sp in object_group[0].object_definition.specialties -%>
<%=      (sp.effects.map{|ef| "#{ef[:target]}:#{sprintf('%+d',ef[:value]*number)}" }).join(',') %>
<%     end -%>
)
</li>
<%b    end -%>
<%   end -%>
<% end %>
</ul>

<b>関連ACE:</b> <%= '(なし)' if @character.bonds.size == 0 %> 
<% if @character.bonds.size > 0 %>
<br/>
<ul>
<%   for bond in @character.bonds
  next if bond.ace.nil?
-%>
  <li><%= bond.bond_type %> ： <%= link_to (bond.ace.character_no ? bond.ace.character_no + '：' : '') + bond.ace.name ,bond.ace%> </li>
<%    end  -%>
</ul>
<% end -%>


<ul><li><%= link_to '[関連ACE一覧]' , character_bonds_path(@character) %></li></ul>

  <p>
    <b><%= link_to 'イグドラシル' , owner_account_yggdrasills_path(@character.owner_account) %></b>
  </p>
  <p>
    <b><%= link_to 'コマンドリソース' , owner_account_command_resources_path(@character.owner_account) %></b>
  </p>
  <p>
    <b><%= link_to 'ユニット登録（コンバート・インクルード）' , owner_account_unit_registries_path(@character.owner_account) %></b>
  </p>
<hr/>
<ul>
       <% if has_role?(:herald) %>
  <li> <%= link_to "個人詳細編集" , :action => :edit , :controller => :characters , :nation_id => @character.nation , :id => @character %> </li>
  <li> <%= link_to "根源力編集" , :action => :edit_result , :controller => :characters , :nation_id => @character.nation , :id => @character %> </li>
       <% end %>
  <li> <%= link_to '編集履歴' , owner_account_modify_commands_path(@character.owner_account) %> </li>
</ul>



<% @nation_id = @character.nation_id%>